// <auto-generated />
using System;
using KossanVMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KossanVMS.Migrations
{
    [DbContext(typeof(VmsContext))]
    [Migration("20250924022426_InitAligned")]
    partial class InitAligned
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KossanVMS.Data.VisitBranch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"), 1L, 1);

                    b.Property<bool>("BranchContract")
                        .HasColumnType("bit");

                    b.Property<string>("BranchDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("BranchStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchID");

                    b.HasIndex("BranchName")
                        .IsUnique();

                    b.ToTable("VisitBranches");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<bool>("CategoryContract")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("VisitCategories");
                });

            modelBuilder.Entity("KossanVMS.Data.Visitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorID"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ICNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VisitorID");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorBlackList", b =>
                {
                    b.Property<int>("VisitorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlackList")
                        .HasColumnType("bit");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitorID");

                    b.ToTable("VisitorBlackList");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorCompany", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"), 1L, 1);

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VisitorID")
                        .HasColumnType("int");

                    b.HasKey("CompanyID");

                    b.HasIndex("VisitorID")
                        .IsUnique();

                    b.ToTable("VisitorCompanies");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorContact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitorID")
                        .HasColumnType("int");

                    b.HasKey("ContactID");

                    b.HasIndex("VisitorID")
                        .IsUnique();

                    b.ToTable("VisitorContacts");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorPhoto", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoID"), 1L, 1);

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VisitorID")
                        .HasColumnType("int");

                    b.HasKey("PhotoID");

                    b.HasIndex("VisitorID")
                        .IsUnique();

                    b.ToTable("VisitorPhotos");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitPurpose", b =>
                {
                    b.Property<int>("PurposeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurposeID"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PurposeContract")
                        .HasColumnType("bit");

                    b.Property<string>("PurposeDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PurposeStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PurposeID");

                    b.HasIndex("PurposeName")
                        .IsUnique();

                    b.ToTable("VisitPurpose");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitRecord", b =>
                {
                    b.Property<Guid>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatePass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("InContainer")
                        .HasColumnType("tinyint");

                    b.Property<string>("InContainerNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InPBID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("OutContainer")
                        .HasColumnType("tinyint");

                    b.Property<string>("OutContainerNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutPBID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PurposeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitorID")
                        .HasColumnType("int");

                    b.HasKey("VisitID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PurposeID");

                    b.HasIndex("VisitorID");

                    b.ToTable("VisitRecords");
                });

            modelBuilder.Entity("KossanVMS.Data.VmsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VmsUsers");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorBlackList", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("BlackList")
                        .HasForeignKey("KossanVMS.Data.VisitorBlackList", "VisitorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorCompany", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("Company")
                        .HasForeignKey("KossanVMS.Data.VisitorCompany", "VisitorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorContact", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("Contact")
                        .HasForeignKey("KossanVMS.Data.VisitorContact", "VisitorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitorPhoto", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("Photo")
                        .HasForeignKey("KossanVMS.Data.VisitorPhoto", "VisitorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitRecord", b =>
                {
                    b.HasOne("KossanVMS.Data.VisitBranch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KossanVMS.Data.VisitCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KossanVMS.Data.VisitPurpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("PurposeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithMany("VisitRecords")
                        .HasForeignKey("VisitorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Category");

                    b.Navigation("Purpose");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.Visitor", b =>
                {
                    b.Navigation("BlackList");

                    b.Navigation("Company")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Photo")
                        .IsRequired();

                    b.Navigation("VisitRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
