// <auto-generated />
using System;
using KossanVMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KossanVMS.Migrations
{
    [DbContext(typeof(VmsContext))]
    [Migration("20251110012045_UpdateVmsUserEntity")]
    partial class UpdateVmsUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KossanVMS.Data.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("b_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"), 1L, 1);

                    b.Property<string>("BranchConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("b_connection_string")
                        .HasColumnOrder(4);

                    b.Property<string>("BranchDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("b_description")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("b_name")
                        .HasColumnOrder(1);

                    b.Property<bool>("BranchStatus")
                        .HasColumnType("bit")
                        .HasColumnName("b_status")
                        .HasColumnOrder(3);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("BranchID");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("KossanVMS.Data.BranchLink", b =>
                {
                    b.Property<int>("BranchLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bl_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchLinkID"), 1L, 1);

                    b.Property<int>("BranchID")
                        .HasColumnType("int")
                        .HasColumnName("branch_id")
                        .HasColumnOrder(2);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("BranchLinkID");

                    b.HasIndex("BranchID");

                    b.HasIndex("IdNo");

                    b.ToTable("branch_link");
                });

            modelBuilder.Entity("KossanVMS.Data.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("c_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<bool>("CategoryContract")
                        .HasColumnType("bit")
                        .HasColumnName("c_contract")
                        .HasColumnOrder(4);

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("c_description")
                        .HasColumnOrder(2);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("c_name")
                        .HasColumnOrder(1);

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit")
                        .HasColumnName("c_status")
                        .HasColumnOrder(3);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("CategoryID");

                    b.ToTable("category");
                });

            modelBuilder.Entity("KossanVMS.Data.CategoryLink", b =>
                {
                    b.Property<int>("CategoryLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cl_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryLinkID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasColumnOrder(2);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("CategoryLinkID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("IdNo");

                    b.ToTable("category_link");
                });

            modelBuilder.Entity("KossanVMS.Data.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("c_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"), 1L, 1);

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_address")
                        .HasColumnOrder(2);

                    b.Property<string>("ContactCity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_city")
                        .HasColumnOrder(3);

                    b.Property<string>("ContactCompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_company");

                    b.Property<string>("ContactCompanyNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_company_no");

                    b.Property<string>("ContactPostCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_postcode")
                        .HasColumnOrder(5);

                    b.Property<string>("ContactState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_state")
                        .HasColumnOrder(4);

                    b.Property<string>("ContactTel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_tel")
                        .HasColumnOrder(6);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("ContactID");

                    b.HasIndex("IdNo")
                        .IsUnique();

                    b.ToTable("contact");
                });

            modelBuilder.Entity("KossanVMS.Data.Photo", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("p_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoID"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("PhotoCaptureDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("p_capture_date")
                        .HasColumnOrder(5);

                    b.Property<string>("PhotoCapturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("p_capture_path")
                        .HasColumnOrder(2);

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("p_url")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("PhotoUploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("p_upload_date")
                        .HasColumnOrder(6);

                    b.Property<string>("PhotoUploadPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("p_upload_path")
                        .HasColumnOrder(3);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("PhotoID");

                    b.HasIndex("IdNo")
                        .IsUnique();

                    b.ToTable("photo");
                });

            modelBuilder.Entity("KossanVMS.Data.Purpose", b =>
                {
                    b.Property<int>("PurposeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("p_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurposeID"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<string>("PurposeDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("p_description");

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("p_name");

                    b.Property<bool>("PurposeStatus")
                        .HasColumnType("bit")
                        .HasColumnName("p_status");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("PurposeID");

                    b.HasIndex("IdNo")
                        .IsUnique();

                    b.ToTable("purpose");
                });

            modelBuilder.Entity("KossanVMS.Data.RegisterType", b =>
                {
                    b.Property<int>("RegisterTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rt_type_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterTypeID"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("RegisterTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rt_type_name")
                        .HasColumnOrder(1);

                    b.Property<string>("RegisterUserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rt_user_role")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.HasKey("RegisterTypeID");

                    b.ToTable("register_type");
                });

            modelBuilder.Entity("KossanVMS.Data.Visitor", b =>
                {
                    b.Property<int>("VisitorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("v_no")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorNo"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<bool>("VisitorBlackList")
                        .HasColumnType("bit")
                        .HasColumnName("v_black_list")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("VisitorExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("v_expiry_date")
                        .HasColumnOrder(5);

                    b.Property<string>("VisitorFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("v_full_name")
                        .HasColumnOrder(3);

                    b.Property<string>("VisitorIdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("v_id_no")
                        .HasColumnOrder(1);

                    b.Property<byte>("VisitorIdType")
                        .HasColumnType("tinyint")
                        .HasColumnName("v_id_type")
                        .HasColumnOrder(2);

                    b.HasKey("VisitorNo");

                    b.HasAlternateKey("VisitorIdNo")
                        .HasName("AK_visitors_id_no");

                    b.ToTable("visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitRecord", b =>
                {
                    b.Property<int>("VisitRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vr_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitRecordID"), 1L, 1);

                    b.Property<int?>("BranchID")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("branch_id")
                        .HasColumnOrder(2);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasColumnOrder(3);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visitor_id_no")
                        .HasColumnOrder(1);

                    b.Property<int?>("PurposeID")
                        .HasColumnType("int")
                        .HasColumnName("purpose_id");

                    b.Property<int?>("RegisterTypeID")
                        .HasColumnType("int")
                        .HasColumnName("register_type_id")
                        .HasColumnOrder(5);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<decimal?>("VisitRecordBodyTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("vr_body_temperature")
                        .HasColumnOrder(15);

                    b.Property<int?>("VisitRecordContactContactID")
                        .HasColumnType("int");

                    b.Property<string>("VisitRecordDONo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_do_no")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("VisitRecordExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("vr_expiry_date")
                        .HasColumnOrder(16);

                    b.Property<string>("VisitRecordGatePass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_gate_pass")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("VisitRecordInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("vr_in_time")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("VisitRecordOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("vr_out_time")
                        .HasColumnOrder(7);

                    b.Property<string>("VisitRecordPhotoPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_photo_path")
                        .HasColumnOrder(10);

                    b.Property<string>("VisitRecordRemarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_remarks")
                        .HasColumnOrder(9);

                    b.Property<string>("VisitRecordTagNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_tag_no")
                        .HasColumnOrder(11);

                    b.Property<string>("VisitRecordVehicleNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_vehicle_no")
                        .HasColumnOrder(8);

                    b.Property<string>("VisitRecordVisitPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vr_visit_person")
                        .HasColumnOrder(13);

                    b.HasKey("VisitRecordID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("IdNo");

                    b.HasIndex("PurposeID");

                    b.HasIndex("RegisterTypeID");

                    b.HasIndex("VisitRecordContactContactID");

                    b.ToTable("visit_record");
                });

            modelBuilder.Entity("KossanVMS.Data.VmsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_salt");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("user_role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("vms_users", "dbo");
                });

            modelBuilder.Entity("KossanVMS.Data.BranchLink", b =>
                {
                    b.HasOne("KossanVMS.Data.Branch", "BranchLinkBranch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KossanVMS.Data.Visitor", "BranchLinkVisitor")
                        .WithMany("VisitorBranches")
                        .HasForeignKey("IdNo")
                        .HasPrincipalKey("VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchLinkBranch");

                    b.Navigation("BranchLinkVisitor");
                });

            modelBuilder.Entity("KossanVMS.Data.CategoryLink", b =>
                {
                    b.HasOne("KossanVMS.Data.Category", "CategoryLinkCategory")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KossanVMS.Data.Visitor", "CategoryLinkVisitor")
                        .WithMany("VisitorCategories")
                        .HasForeignKey("IdNo")
                        .HasPrincipalKey("VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryLinkCategory");

                    b.Navigation("CategoryLinkVisitor");
                });

            modelBuilder.Entity("KossanVMS.Data.Contact", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("VisitorContact")
                        .HasForeignKey("KossanVMS.Data.Contact", "IdNo")
                        .HasPrincipalKey("KossanVMS.Data.Visitor", "VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.Photo", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("VisitorPhoto")
                        .HasForeignKey("KossanVMS.Data.Photo", "IdNo")
                        .HasPrincipalKey("KossanVMS.Data.Visitor", "VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.Purpose", b =>
                {
                    b.HasOne("KossanVMS.Data.Visitor", "Visitor")
                        .WithOne("VisitorPurpose")
                        .HasForeignKey("KossanVMS.Data.Purpose", "IdNo")
                        .HasPrincipalKey("KossanVMS.Data.Visitor", "VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("KossanVMS.Data.VisitRecord", b =>
                {
                    b.HasOne("KossanVMS.Data.Branch", "VisitRecordBranch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KossanVMS.Data.Category", "VisitRecordCategory")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KossanVMS.Data.Visitor", "VisitRecordVisitor")
                        .WithMany("VisitRecords")
                        .HasForeignKey("IdNo")
                        .HasPrincipalKey("VisitorIdNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KossanVMS.Data.Purpose", "VisitRecordPurpose")
                        .WithMany()
                        .HasForeignKey("PurposeID");

                    b.HasOne("KossanVMS.Data.RegisterType", "VisitRecordRegisterType")
                        .WithMany()
                        .HasForeignKey("RegisterTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KossanVMS.Data.Contact", "VisitRecordContact")
                        .WithMany()
                        .HasForeignKey("VisitRecordContactContactID");

                    b.Navigation("VisitRecordBranch");

                    b.Navigation("VisitRecordCategory");

                    b.Navigation("VisitRecordContact");

                    b.Navigation("VisitRecordPurpose");

                    b.Navigation("VisitRecordRegisterType");

                    b.Navigation("VisitRecordVisitor");
                });

            modelBuilder.Entity("KossanVMS.Data.Visitor", b =>
                {
                    b.Navigation("VisitRecords");

                    b.Navigation("VisitorBranches");

                    b.Navigation("VisitorCategories");

                    b.Navigation("VisitorContact");

                    b.Navigation("VisitorPhoto");

                    b.Navigation("VisitorPurpose");
                });
#pragma warning restore 612, 618
        }
    }
}
